baseURL = 'http://blog.iamqh.me'
languageCode = 'vi-vn'
title = "iamqh's Blog"
theme = 'PaperMod'

[params]
env = 'development'
title = "iamqh's Blog"
author = "iamqh"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

    [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Write code, love life!"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://facebook.com/phamquang.hoa.79"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://stackoverflow.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/HoaPham98"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20
